version: '3'  # version of compose format 

services:
  poem-generator:
    build: ./poet  # path is relative to docker-compose.yml localtion
    volumes:
      - ./poet:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html # mount
    ports:
      - 5000:80  # host:container
    depends_on:
      - poem-generator  # website is not going to work 
                             # unless observatory-service is running